spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

springdoc:
  swagger-ui:
    enabled: false

logging:
  level:
    com.agency.backend: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
  file:
    name: logs/agency-backend.log
